### ISSUE TITLE
Changes break put function

### ISSUE THREAD

**Issue by archangelic** [m455/elafint#3]
https://github.com/m455/elafint/blob/fcfc92132ad9e0e5c578170b0218958027ce4fdb/elafint.py#L73

recent commits mean that the put function will no longer work. Needs to be changed to `use(place(x, y) + bold + fg + bg + text + RESET_ALL)`

**Comment by m455** [comment]
I think I removed your put function by accident and the .gitignore, but i managed to get it all back now. I also changed what you said above accordingly just now. maybe we can create two place functions for now until we figure out which way will be best in the end as well
